repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make check-format
        language: system
        types: [python]
        stages: [commit, push]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: make smell
        language: system
        types: [python]
        stages: [commit, push]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: make typecheck
        language: system
        types: [python]
        stages: [commit, push]

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: make test
        language: system
        types: [python]
        stages: [push]